USE [master]
GO
/****** Object:  Database [IssdTP4Clase05]    Script Date: 03/10/2023 18:46:17 ******/
CREATE DATABASE [IssdTP4Clase05]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IssdTP4Clase05', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\IssdTP4Clase05.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IssdTP4Clase05_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\IssdTP4Clase05_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [IssdTP4Clase05] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IssdTP4Clase05].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [IssdTP4Clase05] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET ARITHABORT OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [IssdTP4Clase05] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [IssdTP4Clase05] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET  DISABLE_BROKER 
GO
ALTER DATABASE [IssdTP4Clase05] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [IssdTP4Clase05] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [IssdTP4Clase05] SET  MULTI_USER 
GO
ALTER DATABASE [IssdTP4Clase05] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [IssdTP4Clase05] SET DB_CHAINING OFF 
GO
ALTER DATABASE [IssdTP4Clase05] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [IssdTP4Clase05] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [IssdTP4Clase05] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [IssdTP4Clase05] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [IssdTP4Clase05] SET QUERY_STORE = ON
GO
ALTER DATABASE [IssdTP4Clase05] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [IssdTP4Clase05]
GO
/****** Object:  Table [dbo].[Cuentas]    Script Date: 03/10/2023 18:46:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cuentas](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[descripcion] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Cuentas] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RegistrosContables]    Script Date: 03/10/2023 18:46:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RegistrosContables](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idCuenta] [int] NULL,
	[monto] [int] NOT NULL,
	[tipo] [bit] NOT NULL,
 CONSTRAINT [PK_RegistrosContables] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Cuentas] ON 
GO
INSERT [dbo].[Cuentas] ([id], [descripcion]) VALUES (1, N'Cuenta A')
GO
INSERT [dbo].[Cuentas] ([id], [descripcion]) VALUES (2, N'Cuenta B')
GO
INSERT [dbo].[Cuentas] ([id], [descripcion]) VALUES (5, N'Cuenta C')
GO
INSERT [dbo].[Cuentas] ([id], [descripcion]) VALUES (6, N'Cuenta D')
GO
SET IDENTITY_INSERT [dbo].[Cuentas] OFF
GO
SET IDENTITY_INSERT [dbo].[RegistrosContables] ON 
GO
INSERT [dbo].[RegistrosContables] ([id], [idCuenta], [monto], [tipo]) VALUES (1, 1, 1000, 0)
GO
INSERT [dbo].[RegistrosContables] ([id], [idCuenta], [monto], [tipo]) VALUES (2, 2, 2500, 0)
GO
INSERT [dbo].[RegistrosContables] ([id], [idCuenta], [monto], [tipo]) VALUES (3, 5, 3000, 1)
GO
SET IDENTITY_INSERT [dbo].[RegistrosContables] OFF
GO
ALTER TABLE [dbo].[RegistrosContables]  WITH CHECK ADD FOREIGN KEY([idCuenta])
REFERENCES [dbo].[Cuentas] ([id])
GO
USE [master]
GO
ALTER DATABASE [IssdTP4Clase05] SET  READ_WRITE 
GO
